# #+TITLE: Assignment description: Thesis project
# #+AUTHOR: Axel Demborg \texttt{demborg@kth}
# #+OPTIONS: toc:nil 1 num:nil

* Preliminary thesis title
Efficient object segmentation on mobile phones

* Background/Conditions
For 3D scanning of human bodies specialized hardware has traditionally been used. With the resent developments in segmentation and spacial understanding for convolutional neural networks, high performance 3D modeling might be achievable with commodity hardware such as high end smartphones. This will be evaluated in this project.

The project will be carried out at Volumental a Stockholm based computer vision company from RPL, KTH active in 3D body scanning and product recommendation based on 3D measurements in footwear.

* Research questions
Since AlexNet published in 2012, Convolutional Neural Networks has
ushered a new era in computer vision, consistently improving object
detection and segmentation accuracy. In image segmentation, the latest
promising work on this front is Mask R-CNN, a region proposing network
for object segmentation, building upon a series of CNNs for object
detection[fn:1]. This Msc thesis is about implementing Mask R-CNN that
can run on flagship iPhone with the end goal of 3D scanning human
bodies. As such, the thesis combines theoretical understanding of CNNs
with the practice of running it on mobile devices.

It is reasonable to expect that results from this thesis will be comparable to but not as good as results from dedicated hardware. Evaluation will be performed against Volumental's preexisting datasets of feet scanned using the companies own scanner.

* Background of the degree project student
As a masters student in machine learning with a specialization in deep learning from the courses ID2223 (Scalable Machine Learning and Deep Learning) and DD2424 (Deep Learning in Data Science) as well as experience with 3D modeling from DD2429 (Computational Photography) I feel very well suited for this project.

* Supervisor at the company
The supervisor at the company will be Alper Aydemir Co-founder and CTO of the company. He has a PhD from RPL at KTH and has experience in 3D modeling and computer vision from both JPL and Google X.  

* Limits/Resources
The company has extensive expertise in computer vision and machine learning as well as datasets for 3D modeling. Thus there is a solid foundation in place to build the thesis upon.
  
* Eligibility and study planing
I assure that I have completed all courses up until this point, this includes all the courses from the bachelors' degree, the course in scientific theory and method as well as all the courses relevant for the thesis. This sums up to over 60 points of second cycle courses and since no courses are remaining there is nothing to plan for those.

* Footnotes

[fn:1] [[https://blog.athelas.com/a-brief-history-of-cnns-in-image-segmentation-from-r-cnn-to-mask-r-cnn-34ea83205de4][A brief history of CNNS in image segmentation]]



